/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiply_12 (
    input [5:0] alufn_signal,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (alufn_signal[0+2-:3])
      3'h0: begin
        out = a * b;
      end
      3'h7: begin
        out = a / b;
      end
    endcase
  end
endmodule
